export enum BrazilianDDDEnum {
    "AC" = 68, // Acre
    "AL" = 82, // Alagoas
    "AP" = 96, // Amapá
    "AM" = 92, // Amazonas
    "BA" = 71, // Bahia
    "BA2" = 73, // Bahia - Região 2
    "BA3" = 74, // Bahia - Região 3
    "BA4" = 75, // Bahia - Região 4
    "BA5" = 77, // Bahia - Região 5
    "CE" = 85, // Ceará
    "CE2" = 88, // Ceará - Região 2
    "DF" = 61, // Distrito Federal
    "ES" = 27, // Espírito Santo
    "ES2" = 28, // Espírito Santo - Região 2
    "GO" = 62, // Goiás
    "GO2" = 64, // Goiás - Região 2
    "MA" = 98, // Maranhão
    "MA2" = 99, // Maranhão - Região 2
    "MT" = 65, // Mato Grosso
    "MT2" = 66, // Mato Grosso - Região 2
    "MS" = 67, // Mato Grosso do Sul
    "MG" = 31, // Minas Gerais
    "MG2" = 32, // Minas Gerais - Região 2
    "MG3" = 33, // Minas Gerais - Região 3
    "MG4" = 34, // Minas Gerais - Região 4
    "MG5" = 35, // Minas Gerais - Região 5
    "MG6" = 37, // Minas Gerais - Região 6
    "MG7" = 38, // Minas Gerais - Região 7
    "PA" = 91, // Pará
    "PA2" = 93, // Pará - Região 2
    "PA3" = 94, // Pará - Região 3
    "PB" = 83, // Paraíba
    "PR" = 41, // Paraná
    "PR2" = 42, // Paraná - Região 2
    "PR3" = 43, // Paraná - Região 3
    "PR4" = 44, // Paraná - Região 4
    "PR5" = 45, // Paraná - Região 5
    "PR6" = 46, // Paraná - Região 6
    "PE" = 81, // Pernambuco
    "PE2" = 87, // Pernambuco - Região 2
    "PI" = 86, // Piauí
    "PI2" = 89, // Piauí - Região 2
    "RJ" = 21, // Rio de Janeiro
    "RJ2" = 22, // Rio de Janeiro - Região 2
    "RJ3" = 24, // Rio de Janeiro - Região 3
    "RN" = 84, // Rio Grande do Norte
    "RS" = 51, // Rio Grande do Sul
    "RS2" = 53, // Rio Grande do Sul - Região 2
    "RS3" = 54, // Rio Grande do Sul - Região 3
    "RS4" = 55, // Rio Grande do Sul - Região 4
    "RO" = 69, // Rondônia
    "RR" = 95, // Roraima
    "SC" = 47, // Santa Catarina
    "SC2" = 48, // Santa Catarina - Região 2
    "SC3" = 49, // Santa Catarina - Região 3
    "SP" = 11, // São Paulo
    "SP2" = 12, // São Paulo - Região 2
    "SP3" = 13, // São Paulo - Região 3
    "SP4" = 14, // São Paulo - Região 4
    "SP5" = 15, // São Paulo - Região 5
    "SP6" = 16, // São Paulo - Região 6
    "SP7" = 17, // São Paulo - Região 7
    "SP8" = 18, // São Paulo - Região 8
    "SP9" = 19, // São Paulo - Região 9
    "SE" = 79, // Sergipe
    "TO" = 63 // Tocantins
}
